### ISSUE TITLE
[Crash] mouseReleased event handler

### ISSUE THREAD

**Issue by moninformateur** [caeruleusDraconis/world-preview#6] opened 2023-08-05 17:07 UTC
This happens on the preview screen when adding a new seed or generating a random one.

Complete log and modlist available on **[mclo.gs](https://mclo.gs/ZvW2mbC)**

Thank you!

**Comment by Taiterio** [comment] 2023-08-05 22:05
Thank you for the report!
Could you try to provide us a pack of the mods you are using?
I was unable to reproduce the error in the base forge version.

I have included a BETA version that includes a [fix](https://github.com/caeruleusDraconis/world-preview/commit/b0d31fcf6499b552292493f4d89dade12474ff97) for the error in the log, though I am unsure if there are further errors past that.
[world_preview-1.0.1-BETA.zip](https://github.com/caeruleusDraconis/world-preview/files/12268294/world_preview-1.0.1-BETA.zip)

**Comment by caeruleusDraconis** [comment] 2023-08-17 10:24
Should now also be fixed with the latest release.

**Closed as completed by caeruleusDraconis** 2023-08-17 10:24 UTC
