### ISSUE TITLE
forge 47.2.0 minecraft 1.20.1

### ISSUE THREAD

**Issue by Thunderrock424242** [caeruleusDraconis/world-preview#24] opened 2024-02-04 21:01 UTC
### What happened?

crashed when loading a preview on a new world

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Forge

### World-Preview Version

1.1.5

### Minecraft Logs

[latest.log](https://github.com/caeruleusDraconis/world-preview/files/14158465/latest.log)

**Comment by caeruleusDraconis** [comment] 2024-02-05 19:56
This should (hopefully) be fixed in the next release. Could you please check if the attached version from my comment fixes the issue?

Sadly, I am unable to reproduce the bug locally due to the extensive mod list. If you are using a public mod-pack, it would help me a lot debugging this issue if you could provide a link to it.

**Comment by Thunderrock424242** [comment] 2024-02-05 23:05
> This should (hopefully) be fixed in the next release. Could you please check if the attached version from my comment fixes the issue?
> 
> Sadly, I am unable to reproduce the bug locally due to the extensive mod list. If you are using a public mod-pack, it would help me a lot debugging this issue if you could provide a link to it.

[link to modpack is here ](https://www.curseforge.com/minecraft/modpacks/wilderness-odyssey)

**Comment by caeruleusDraconis** [comment] 2024-02-13 13:09
I was unable to reproduce this specific bug with the linked modpack alone. However, it should be fixed with [`1.2.0`](https://modrinth.com/mod/world-preview/version/1.2.0).

**Comment by Thunderrock424242** [comment] 2024-02-13 17:31
Ok

**Comment by Thunderrock424242** [comment] 2024-02-22 21:32
Seems to have fixed it

**Closed as completed** 2024-02-22 21:32 UTC
Labels: bug
