### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2874.comp_651()" because "this.dimensionType" is null

### ISSUE THREAD

**Issue by ZekerZhayard** [caeruleusDraconis/world-preview#22] opened 2024-01-05 05:58 UTC
### What happened?

Game crashed

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.1.5

### Minecraft Logs

https://paste.ubuntu.com/p/bv6WzKtP8C/

**Comment by caeruleusDraconis** [comment] 2024-01-07 17:26
I am unable to reproduce this in vanilla + fabric API + World Preview --> This is likely a compatibility issue with another mod. Are you using a public mod pack I can download to reproduce this? Alternatively, could you please try finding out witch mod specifically causes this behavior?

I have created a build that should at least fix the `NullPointerException`: [world_preview.zip](https://github.com/caeruleusDraconis/world-preview/files/13854284/world_preview-1.zip). Could you please check build fixes the issue or if there are other issues?

**Comment by caeruleusDraconis** [comment] 2024-02-13 13:07
Should be fixed with [`1.2.0`](https://modrinth.com/mod/world-preview/version/ulplldFu)

**Closed as completed by caeruleusDraconis** 2024-02-13 13:07 UTC
Labels: bug, needs more info
